var Courses_Orig = [
    {name: "Tsukuba", weeks: 0, reverse: false, maxcars: 6},
    {name: "Fuji Speedway 90's", weeks: 0, reverse: false, maxcars: 6},
    {name: "Infineon Raceway - Sports Car", weeks: 0, reverse: false, maxcars: 6},
    {name: "Laguna Seca", weeks: 0, reverse: false, maxcars: 6},
    {name: "Twin Ring Motegi West Short", weeks: 0, reverse: false, maxcars: 6},
    {name: "Twin Ring Motegi Super Speedway", weeks: 0, reverse: false, maxcars: 6},
    {name: "Suzuka Circuit East", weeks: 0, reverse: false, maxcars: 6},
    {name: "Nurburgring Nordschleife", weeks: 0, reverse: false, maxcars: 6},
    {name: "Seoul Central", weeks: 0, reverse: true, maxcars: 6},
    {name: "Tokyo Route 246", weeks: 0, reverse: true, maxcars: 6},
    {name: "Clubman Stage Route 5", weeks: 0, reverse: true, maxcars: 6},
    {name: "New York", weeks: 0, reverse: true, maxcars: 6},
    {name: "Seattle Circuit", weeks: 0, reverse: true, maxcars: 6},
    {name: "Citta di Aria", weeks: 0, reverse: true, maxcars: 2},
    {name: "Driving Park Motorland", weeks: 0, reverse: true, maxcars: 6},
    {name: "Driving Park Beginner Course", weeks: 0, reverse: true, maxcars: 6},
    {name: "High-Speed Ring", weeks: 0, reverse: true, maxcars: 6},
    {name: "Mid-Field Raceway", weeks: 0, reverse: true, maxcars: 6},
    {name: "Grand Valley East", weeks: 0, reverse: true, maxcars: 6},
    {name: "Trial Mountain Circuit", weeks: 0, reverse: true, maxcars: 6},
    {name: "El Capitan", weeks: 0, reverse: true, maxcars: 6},
    {name: "Autumn Ring Mini", weeks: 0, reverse: true, maxcars: 6},
    {name: "Swiss Alps", weeks: 0, reverse: true, maxcars: 2},
    {name: "Cathedral Rocks Trail II", weeks: 0, reverse: true, maxcars: 2},
    {name: "Grand Canyon", weeks: 0, reverse: false, maxcars: 2},
    {name: "Deep Forest Raceway", weeks: 2, reverse: true, maxcars: 6},
    {name: "Opera Paris", weeks: 4, reverse: true, maxcars: 6},
    {name: "Fuji Speedway 80's", weeks: 6, reverse: false, maxcars: 6},
    {name: "Special Stage Route 5", weeks: 8, reverse: true, maxcars: 6},
    {name: "Suzuka Circuit Full", weeks: 10, reverse: false, maxcars: 6},
    {name: "Twin Ring Motegi East Short", weeks: 12, maxcars: 6},
    {name: "Grand Valley Speedway", weeks: 14, reverse: true, maxcars: 6},
    {name: "Hong Kong", weeks: 16, reverse: true, maxcars: 6},
    {name: "Suzuka Circuit West", weeks: 18, reverse: false, maxcars: 6},
    {name: "Fuji Speedway 2005 GT", weeks: 20, reverse: false, maxcars: 6},
    {name: "Ice Arena", weeks: 22, reverse: true, maxcars: 2},
    {name: "Apricot Hill Raceway", weeks: 24, reverse: true, maxcars: 6},
    {name: "Cote d'Azur", weeks: 26, reverse: false, maxcars: 6},
    {name: "Tahiti Maze", weeks: 28, reverse: true, maxcars: 6},
    {name: "Twin Ring Motegi Full Road", weeks: 30, reverse: false, maxcars: 6},
    {name: "George V Paris", weeks: 32, reverse: true, maxcars: 2},
    {name: "Cathedral Rocks Trail I", weeks: 34, reverse: true, maxcars: 2},
    {name: "Costa di Amalfi", weeks: 36, reverse: true, maxcars: 2},
    {name: "Circuit de la Sarthe I", weeks: 38, reverse: false, maxcars: 6},
    {name: "Autumn Ring", weeks: 40, reverse: true, maxcars: 6},
    {name: "Infineon Raceway - Stock Car", weeks: 42, reverse: false, maxcars: 6},
    {name: "Chamonix", weeks: 44, reverse: true, maxcars: 2},
    {name: "Fuji Speedway 2005 F", weeks: 46, reverse: false, maxcars: 6},
    // weirdly you can do Family Cup at Tsukuba WET, but whatever
    {name: "Tsukuba WET", weeks: 48, reverse: false, maxcars: 2},
    {name: "Circuit de la Sarthe II", weeks: 50, reverse: false, maxcars: 6},
];