var Events_Orig = {
	"rally": [
		"Umbria Rally",
		"Capri Rally",
		"Grand Canyon Rally",
		"Whistler Ice Race",
		"Chamonix Rally",
		"George V Rally",
		"Swiss Alps Rally",
		"Tour of Tahiti",
		"Tsukuba Wet Race",
		"Yosemite Rally I",
		"Yosemite Rally II",
	],
	"-": [
		"Sunday Cup",
		"FF Challenge",
		"FR Challenge",
		"4WD Challenge",
		"MR Challenge",
		"Lightweight K-Car Cup",
		"Sports Truck Race",
		"Lotus Classics",
		"Mini Mini Sports Meeting",
		"2HP - 2CV Classics",
		"A3 Cup",
		"1 Series Trophy",
		"GTA Cup",
		"Midget II Race",
		"Isuzu Sports Classics",
		"Mirage Cup",
		"Suzuki Concepts",
		"Vitz Race",
	],
	"b": [
		"Spider & Roadster",
		"Clubman Cup",
		"Race of NA Sports",
		"Race of Turbo Sports",
		"Race of Boxer Spirit",
		"Muscle Car Competition",
		"British Lightweight Series",
		"Japanese 70's Classics",
		"Japanese Compact Cup",
		"Camaro Meeting",
		"Aston Martin Carnival",
		"Tourist Trophy",
		"Beetle Cup",
		"GTi Cup",
		"Hyundai Sports Festival",
		"Civic Race",
		"Club \"RE\"",
		"NR-A Roadster Cup",
		"NR-A RX-8 Cup",
		"Evolution Meeting",
		"March Brothers",
		"Silvia Sisters",
		"Suzuki K-Car Cup",
		"Altezza Race",
	],
	"a": [
		"Tuning Car Grand Prix",
		"All American Championship",
		"Hot Rod Competition",
		"Tous France Championnat",
		"Schwarzwald Liga A",
		"Japan Championship",
		"Japanese 80's Festival",
		"Japanese 90's Challenge",
		"Crossfire Trophy",
		"Elise Trophy",
		"MG Festival",
		"Black Pool Racers",
		"Spitfire Cup",
		"Renault Alpine Cup",
		"Megane Cup",
		"Club \"M\"",
		"Legends of the Silver Arrow",
		"Lupo Cup",
		"Copen Race",
		"Club \"Z\"",
		"Subaru 360 Race",
	],
	"ib": [
		"World Classic Car Series",
		"World Compact Car Race",
		"Stars and Stripes",
		"Pan Euro Championship",
		"La Festa Italiano",
		"Europe Classic Car League",
		"Euro Hot Hatch League",
		"Schwarzwald Liga B",
		"Vette! Vette! Vette!",
		"Saleen S7 Club",
		"Shelby Cobra Cup",
		"206 Cup",
		"Clio Trophy",
		"SL Challenge",
		"Speedster Trophy",
		"Type R Meeting",
		"Stars of Pleiades",
	],
	"ia": [
		"Supercar Festival",
		"British GT Series",
		"Deutsche Touring Car Meisterschaft",
		"All Japan GT Championship",
		"Race of the Red \"R\" Emblem",
	],
	"extreme": [
		// GTWC has basically the same requirements as extreme hall, so
		"Gran Turismo World Championship",
		"Gran Turismo All Stars",
		"World Circuit Tour",
		"Premium Sports Lounge",
	],
	"s": [
		"Dream Car Championship",
		"Polyphony Digital Cup",
		"Like The Wind",
		"Formula GT World Championship",
	],
	"mission_ib": {
		"The Pass": 10,
	},
	"mission_ia": {
		"3 Lap Battle": 10,
		"Slipstream Battle": 4,
		"1 Lap Magic": 10,
	}
}